server:
  port: 8081

sap:
  jco:
    sysnr: "00"
    user: ""
    passwd: ""
    lang: "en"
    poolCapacity: "3"
    peakLimit: "10"
---
spring:
  profiles: dev.win
sap:
  jco:
    ashost: "/H/1.1.1.1/W/FunkyChicken99/H/2.2.2.2/S/3200"
    client: "700"
---
spring:
  profiles: dev.mac
sap:
  jco:
    ashost: "1.1.1.1"
    client: "700"
---
spring:
  profiles: uat.win
sap:
  jco:
    ashost: "/H/1.1.1.1/W/FunkyChicken99/H/2.2.2.2/S/3200"
    client: "200"
---
spring:
  profiles: uat.mac
sap:
  jco:
    ashost: "/H/1.1.1.1/W/FunkyChicken99/H/2.2.2.2/S/3200"
    client: "200"
